# Generated by Django 3.2.13 on 2022-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baserow_enterprise", "0009_roleassignment_subject_and_scope_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(db_index=True, null=True)),
                (
                    "user_email",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, null=True
                    ),
                ),
                ("group_id", models.PositiveIntegerField(db_index=True, null=True)),
                (
                    "group_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=160, null=True
                    ),
                ),
                ("action_id", models.PositiveIntegerField(db_index=True, null=True)),
                ("action_type", models.TextField(db_index=True)),
                ("action_params", models.JSONField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["user_email", "group_name", "action_type", "timestamp"],
                name="baserow_ent_user_em_972a15_idx",
            ),
        ),
    ]
