# Generated by Django 3.2.13 on 2023-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baserow_enterprise", "0015_alter_team_workspace"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlogentry",
            name="baserow_ent_action__8db5d6_idx",
        ),
        migrations.RenameField(
            model_name="auditlogentry",
            old_name="group_id",
            new_name="workspace_id",
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["-action_timestamp", "user_id", "workspace_id", "action_type"],
                name="baserow_ent_action__ca13aa_idx",
            ),
        ),
    ]
