# Generated by Django 3.2.13 on 2023-02-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baserow_enterprise", "0016_auto_20230222_1556"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlogentry",
            old_name="group_name",
            new_name="workspace_name",
        ),
    ]
