# Generated by Django 3.2.13 on 2023-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baserow_enterprise", "0017_rename_group_name_auditlogentry_workspace_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogexportjob",
            name="filter_workspace_id",
            field=models.PositiveIntegerField(
                help_text="Optional: The workspace to filter the audit log by.",
                null=True,
            ),
        ),
    ]
