receivers:
  otlp:
    protocols:
      grpc: # port 4317
      http: # port 4318

processors:
  # Disable sending spans for the sync templates task as it contains a huge number
  # which pointlessly uses up resource limits.
  filter:
    traces:
      span:
        - 'IsMatch(name, ".*sync_templates_task.*") == true'
      spanevent:
        - 'IsMatch(name, ".*sync_templates_task.*") == true'
  batch:
    send_batch_size: 900
    send_batch_max_size: 1000
  # memory_limiter:
  #   # 80% of maximum memory up to 2G
  #   limit_mib: 1500
  #   # 25% of limit up to 2G
  #   spike_limit_mib: 512
  #   check_interval: 5s
  #
  #   # 50% of the maximum memory
  #   limit_percentage: 50
  #   # 20% of max memory usage spike expected
  #   spike_limit_percentage: 20

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
  otlp/metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
