# Generated by Django 3.2.13 on 2022-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0094_exportjob_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="duplicatefieldjob",
            name="user_ip_address",
            field=models.CharField(
                help_text="The user IP address.", max_length=45, null=True
            ),
        ),
        migrations.AddField(
            model_name="duplicatetablejob",
            name="user_ip_address",
            field=models.CharField(
                help_text="The user IP address.", max_length=45, null=True
            ),
        ),
    ]
