# Generated by Django 3.2.13 on 2023-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0101_add_date_show_tzinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="createdonfield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datefield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formulafield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lastmodifiedfield",
            name="date_force_timezone",
            field=models.CharField(
                help_text="Force a timezone for the field overriding user profile settings.",
                max_length=255,
                null=True,
            ),
        ),
    ]
