# Generated by Django 3.2.13 on 2022-12-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_group_storage_usage_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="can_be_undone",
            field=models.BooleanField(default=True),
        ),
    ]
