# Generated by Django 3.2.13 on 2023-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_add_ip_address_to_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("SIGNED_IN", "Signed in"),
                    ("REFRESHED_TOKEN", "Refreshed token"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="userlogentry",
            index=models.Index(
                fields=["timestamp", "action", "actor"],
                include=("id",),
                name="user_log_entry_tstamp_act_idx",
            ),
        ),
    ]
