# Generated by Django 3.2.13 on 2023-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_add_ip_address_to_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="last_formula_periodic_update_at",
            field=models.DateTimeField(null=True),
        ),
    ]
