# Generated by Django 3.2.13 on 2023-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_rename_group_template_workspace"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="trashentry",
            name="core_trashe_trashed_0bf61a_idx",
        ),
        migrations.RenameField(
            model_name="trashentry",
            old_name="group",
            new_name="workspace",
        ),
        migrations.AddIndex(
            model_name="trashentry",
            index=models.Index(
                fields=["-trashed_at", "trash_item_type", "workspace", "application"],
                name="core_trashe_trashed_fd28ba_idx",
            ),
        ),
    ]
